---
name: 'CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 5 * *'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        os: ['alpine3.22', 'rockylinux9', 'noble', 'bookworm', 'bookworm-slim']
        version: [11]
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'docker/setup-qemu-action@v1'
      - uses: 'docker/setup-buildx-action@v1'

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push image'
        uses: 'docker/build-push-action@v6'
        with:
          context: '{{defaultContext}}:Dockerfiles/${{ matrix.version }}/${{ matrix.os }}/'
          file: 'Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: 'lacrif/ansible:${{ matrix.version }}-${{ matrix.os }}'
